# Generated by Django 3.2.11 on 2022-01-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teaher',
            new_name='Teacher',
        ),
    ]
