# Generated by Django 3.2.11 on 2022-01-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_rename_teaher_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='bookingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='stayingEnd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='stayingStart',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='muktomoncho',
            name='bookedBy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='muktomoncho',
            name='bookingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='muktomoncho',
            name='eventDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='muktomoncho',
            name='eventType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='roomNo',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.room'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='roomNo',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.IntegerField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
