# Generated by Django 3.2.11 on 2022-01-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20220126_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomNo',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
