# Generated by Django 3.2.11 on 2022-01-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_room_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNo',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
