# Generated by Django 3.2.11 on 2022-01-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_room_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='accessories',
            field=models.CharField(choices=[('Musical', 'Musical'), ('Computer', 'Computer'), ('Technology', 'Technology'), ('Travelling', 'Travelling'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
