# Generated by Django 3.2.11 on 2022-01-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_organisation_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='roomNo',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.room'),
        ),
    ]
