# Generated by Django 3.2.11 on 2022-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_guest_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
