# Generated by Django 3.2.11 on 2022-01-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_organisation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muktomoncho',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.IntegerField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
