# Generated by Django 3.2.11 on 2022-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20220130_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muktomoncho',
            name='id',
            field=models.AutoField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
