# Generated by Django 3.2.11 on 2022-01-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_alter_muktomoncho_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
